# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pghydro_tools_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PghydroToolsDialogBase(object):
    def setupUi(self, PghydroToolsDialogBase):
        PghydroToolsDialogBase.setObjectName("PghydroToolsDialogBase")
        PghydroToolsDialogBase.resize(679, 633)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/plugins/PghydroTools/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        PghydroToolsDialogBase.setWindowIcon(icon)
        self.tabWidget = QtWidgets.QTabWidget(PghydroToolsDialogBase)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 661, 381))
        self.tabWidget.setMouseTracking(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.groupBox = QtWidgets.QGroupBox(self.tab1)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 201, 341))
        self.groupBox.setObjectName("groupBox")
        self.label_1 = QtWidgets.QLabel(self.groupBox)
        self.label_1.setGeometry(QtCore.QRect(20, 40, 46, 13))
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 46, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 100, 91, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(20, 160, 61, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(20, 190, 46, 13))
        self.label_5.setObjectName("label_5")
        self.lineEdit_host = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_host.setGeometry(QtCore.QRect(100, 30, 91, 20))
        self.lineEdit_host.setObjectName("lineEdit_host")
        self.lineEdit_port = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_port.setGeometry(QtCore.QRect(100, 60, 91, 20))
        self.lineEdit_port.setObjectName("lineEdit_port")
        self.lineEdit_base = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_base.setGeometry(QtCore.QRect(100, 90, 91, 20))
        self.lineEdit_base.setObjectName("lineEdit_base")
        self.lineEdit_user = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_user.setGeometry(QtCore.QRect(100, 150, 91, 20))
        self.lineEdit_user.setObjectName("lineEdit_user")
        self.lineEdit_password = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_password.setGeometry(QtCore.QRect(100, 180, 91, 20))
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.pushButton_connect_database = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_connect_database.setGeometry(QtCore.QRect(10, 270, 181, 61))
        self.pushButton_connect_database.setObjectName("pushButton_connect_database")
        self.lineEdit_schema = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_schema.setGeometry(QtCore.QRect(100, 120, 91, 20))
        self.lineEdit_schema.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_schema.setObjectName("lineEdit_schema")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(20, 130, 46, 16))
        self.label_8.setObjectName("label_8")
        self.pushButton_create_database = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_create_database.setGeometry(QtCore.QRect(10, 220, 181, 41))
        self.pushButton_create_database.setObjectName("pushButton_create_database")
        self.tabWidget.addTab(self.tab1, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_9)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 381, 341))
        self.groupBox_2.setObjectName("groupBox_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 19, 351, 151))
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButton_import_drainage_line = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_import_drainage_line.setGeometry(QtCore.QRect(120, 120, 121, 23))
        self.pushButton_import_drainage_line.setObjectName("pushButton_import_drainage_line")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(10, 20, 151, 31))
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setGeometry(QtCore.QRect(10, 50, 151, 31))
        self.label_9.setObjectName("label_9")
        self.input_drainage_line_table_MapLayerComboBox = QtWidgets.QComboBox(self.groupBox_3)
        self.input_drainage_line_table_MapLayerComboBox.setGeometry(QtCore.QRect(120, 20, 221, 22))
        self.input_drainage_line_table_MapLayerComboBox.setObjectName("input_drainage_line_table_MapLayerComboBox")
        self.input_drainage_line_table_attribute_name_MapLayerComboBox = QtWidgets.QComboBox(self.groupBox_3)
        self.input_drainage_line_table_attribute_name_MapLayerComboBox.setGeometry(QtCore.QRect(120, 50, 221, 22))
        self.input_drainage_line_table_attribute_name_MapLayerComboBox.setObjectName("input_drainage_line_table_attribute_name_MapLayerComboBox")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 180, 351, 151))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_10 = QtWidgets.QLabel(self.groupBox_4)
        self.label_10.setGeometry(QtCore.QRect(10, 20, 151, 31))
        self.label_10.setObjectName("label_10")
        self.pushButton_import_drainage_area = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_import_drainage_area.setGeometry(QtCore.QRect(120, 120, 121, 23))
        self.pushButton_import_drainage_area.setObjectName("pushButton_import_drainage_area")
        self.input_drainage_area_table_MapLayerComboBox = QtWidgets.QComboBox(self.groupBox_4)
        self.input_drainage_area_table_MapLayerComboBox.setGeometry(QtCore.QRect(120, 20, 221, 22))
        self.input_drainage_area_table_MapLayerComboBox.setObjectName("input_drainage_area_table_MapLayerComboBox")
        self.tabWidget.addTab(self.tab_9, "")
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setObjectName("tab2")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab2)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 10, 201, 341))
        self.groupBox_6.setObjectName("groupBox_6")
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_6)
        self.groupBox_8.setGeometry(QtCore.QRect(10, 150, 181, 61))
        self.groupBox_8.setObjectName("groupBox_8")
        self.lineEdit_Check_DrainageLineIsNotSimple = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEdit_Check_DrainageLineIsNotSimple.setGeometry(QtCore.QRect(10, 20, 81, 20))
        self.lineEdit_Check_DrainageLineIsNotSimple.setObjectName("lineEdit_Check_DrainageLineIsNotSimple")
        self.pushButton_MakeDrainageLineSimple = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_MakeDrainageLineSimple.setEnabled(False)
        self.pushButton_MakeDrainageLineSimple.setGeometry(QtCore.QRect(100, 20, 75, 23))
        self.pushButton_MakeDrainageLineSimple.setObjectName("pushButton_MakeDrainageLineSimple")
        self.label_41 = QtWidgets.QLabel(self.groupBox_8)
        self.label_41.setGeometry(QtCore.QRect(10, 40, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_6)
        self.groupBox_9.setGeometry(QtCore.QRect(10, 220, 181, 61))
        self.groupBox_9.setObjectName("groupBox_9")
        self.lineEdit_Check_DrainageLineIsNotValid = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_Check_DrainageLineIsNotValid.setGeometry(QtCore.QRect(10, 20, 81, 20))
        self.lineEdit_Check_DrainageLineIsNotValid.setObjectName("lineEdit_Check_DrainageLineIsNotValid")
        self.pushButton_MakeDrainageLineValid = QtWidgets.QPushButton(self.groupBox_9)
        self.pushButton_MakeDrainageLineValid.setEnabled(False)
        self.pushButton_MakeDrainageLineValid.setGeometry(QtCore.QRect(100, 20, 75, 23))
        self.pushButton_MakeDrainageLineValid.setObjectName("pushButton_MakeDrainageLineValid")
        self.label_42 = QtWidgets.QLabel(self.groupBox_9)
        self.label_42.setGeometry(QtCore.QRect(10, 40, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.pushButton_Check_DrainageLineGeometryConsistencies = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_Check_DrainageLineGeometryConsistencies.setGeometry(QtCore.QRect(60, 50, 75, 23))
        self.pushButton_Check_DrainageLineGeometryConsistencies.setObjectName("pushButton_Check_DrainageLineGeometryConsistencies")
        self.lineEdit_DrainageLinePrecision = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_DrainageLinePrecision.setGeometry(QtCore.QRect(100, 20, 81, 20))
        self.lineEdit_DrainageLinePrecision.setObjectName("lineEdit_DrainageLinePrecision")
        self.label_25 = QtWidgets.QLabel(self.groupBox_6)
        self.label_25.setGeometry(QtCore.QRect(20, 20, 81, 16))
        self.label_25.setObjectName("label_25")
        self.lineEdit_DrainageLineOffset = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_DrainageLineOffset.setGeometry(QtCore.QRect(110, 300, 81, 20))
        self.lineEdit_DrainageLineOffset.setObjectName("lineEdit_DrainageLineOffset")
        self.label_28 = QtWidgets.QLabel(self.groupBox_6)
        self.label_28.setGeometry(QtCore.QRect(20, 300, 81, 16))
        self.label_28.setObjectName("label_28")
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_6)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 80, 181, 61))
        self.groupBox_7.setObjectName("groupBox_7")
        self.lineEdit_Check_DrainageLineIsNotSingle = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_Check_DrainageLineIsNotSingle.setGeometry(QtCore.QRect(10, 20, 81, 20))
        self.lineEdit_Check_DrainageLineIsNotSingle.setObjectName("lineEdit_Check_DrainageLineIsNotSingle")
        self.pushButton_ExplodeDrainageLine = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_ExplodeDrainageLine.setEnabled(False)
        self.pushButton_ExplodeDrainageLine.setGeometry(QtCore.QRect(100, 20, 75, 23))
        self.pushButton_ExplodeDrainageLine.setObjectName("pushButton_ExplodeDrainageLine")
        self.label_43 = QtWidgets.QLabel(self.groupBox_7)
        self.label_43.setGeometry(QtCore.QRect(10, 40, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.groupBox_36 = QtWidgets.QGroupBox(self.tab2)
        self.groupBox_36.setGeometry(QtCore.QRect(220, 10, 221, 341))
        self.groupBox_36.setObjectName("groupBox_36")
        self.pushButton_Check_DrainageLineTopologyConsistencies_1 = QtWidgets.QPushButton(self.groupBox_36)
        self.pushButton_Check_DrainageLineTopologyConsistencies_1.setGeometry(QtCore.QRect(60, 20, 75, 23))
        self.pushButton_Check_DrainageLineTopologyConsistencies_1.setObjectName("pushButton_Check_DrainageLineTopologyConsistencies_1")
        self.groupBox_38 = QtWidgets.QGroupBox(self.groupBox_36)
        self.groupBox_38.setGeometry(QtCore.QRect(10, 50, 201, 61))
        self.groupBox_38.setObjectName("groupBox_38")
        self.lineEdit_Check_DrainageLineWithinDrainageLine = QtWidgets.QLineEdit(self.groupBox_38)
        self.lineEdit_Check_DrainageLineWithinDrainageLine.setGeometry(QtCore.QRect(10, 20, 81, 20))
        self.lineEdit_Check_DrainageLineWithinDrainageLine.setObjectName("lineEdit_Check_DrainageLineWithinDrainageLine")
        self.pushButton_DeleteDrainageLineWithinDrainageLine = QtWidgets.QPushButton(self.groupBox_38)
        self.pushButton_DeleteDrainageLineWithinDrainageLine.setEnabled(False)
        self.pushButton_DeleteDrainageLineWithinDrainageLine.setGeometry(QtCore.QRect(100, 20, 75, 23))
        self.pushButton_DeleteDrainageLineWithinDrainageLine.setObjectName("pushButton_DeleteDrainageLineWithinDrainageLine")
        self.label_44 = QtWidgets.QLabel(self.groupBox_38)
        self.label_44.setGeometry(QtCore.QRect(10, 40, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_44.setFont(font)
        self.label_44.setObjectName("label_44")
        self.groupBox_41 = QtWidgets.QGroupBox(self.groupBox_36)
        self.groupBox_41.setGeometry(QtCore.QRect(10, 120, 201, 61))
        self.groupBox_41.setObjectName("groupBox_41")
        self.lineEdit_Check_DrainageLineOverlapDrainageLine = QtWidgets.QLineEdit(self.groupBox_41)
        self.lineEdit_Check_DrainageLineOverlapDrainageLine.setGeometry(QtCore.QRect(10, 20, 81, 20))
        self.lineEdit_Check_DrainageLineOverlapDrainageLine.setObjectName("lineEdit_Check_DrainageLineOverlapDrainageLine")
        self.label_26 = QtWidgets.QLabel(self.groupBox_41)
        self.label_26.setGeometry(QtCore.QRect(100, 20, 81, 16))
        self.label_26.setObjectName("label_26")
        self.label_45 = QtWidgets.QLabel(self.groupBox_41)
        self.label_45.setGeometry(QtCore.QRect(10, 40, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_45.setFont(font)
        self.label_45.setObjectName("label_45")
        self.groupBox_11 = QtWidgets.QGroupBox(self.groupBox_36)
        self.groupBox_11.setGeometry(QtCore.QRect(10, 190, 201, 61))
        self.groupBox_11.setObjectName("groupBox_11")
        self.lineEdit_Check_DrainageLineLoops = QtWidgets.QLineEdit(self.groupBox_11)
        self.lineEdit_Check_DrainageLineLoops.setGeometry(QtCore.QRect(10, 20, 81, 20))
        self.lineEdit_Check_DrainageLineLoops.setObjectName("lineEdit_Check_DrainageLineLoops")
        self.label_27 = QtWidgets.QLabel(self.groupBox_11)
        self.label_27.setGeometry(QtCore.QRect(100, 20, 81, 16))
        self.label_27.setObjectName("label_27")
        self.label_46 = QtWidgets.QLabel(self.groupBox_11)
        self.label_46.setGeometry(QtCore.QRect(10, 40, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_46.setFont(font)
        self.label_46.setObjectName("label_46")
        self.groupBox_39 = QtWidgets.QGroupBox(self.tab2)
        self.groupBox_39.setGeometry(QtCore.QRect(450, 10, 201, 341))
        self.groupBox_39.setObjectName("groupBox_39")
        self.pushButton_Check_DrainageLineTopologyConsistencies_2 = QtWidgets.QPushButton(self.groupBox_39)
        self.pushButton_Check_DrainageLineTopologyConsistencies_2.setGeometry(QtCore.QRect(60, 20, 75, 23))
        self.pushButton_Check_DrainageLineTopologyConsistencies_2.setObjectName("pushButton_Check_DrainageLineTopologyConsistencies_2")
        self.groupBox_40 = QtWidgets.QGroupBox(self.groupBox_39)
        self.groupBox_40.setGeometry(QtCore.QRect(10, 50, 181, 61))
        self.groupBox_40.setObjectName("groupBox_40")
        self.lineEdit_Check_DrainageLineCrossDrainageLine = QtWidgets.QLineEdit(self.groupBox_40)
        self.lineEdit_Check_DrainageLineCrossDrainageLine.setGeometry(QtCore.QRect(10, 20, 81, 20))
        self.lineEdit_Check_DrainageLineCrossDrainageLine.setObjectName("lineEdit_Check_DrainageLineCrossDrainageLine")
        self.label_47 = QtWidgets.QLabel(self.groupBox_40)
        self.label_47.setGeometry(QtCore.QRect(10, 40, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_47.setFont(font)
        self.label_47.setObjectName("label_47")
        self.groupBox_42 = QtWidgets.QGroupBox(self.groupBox_39)
        self.groupBox_42.setGeometry(QtCore.QRect(10, 120, 181, 61))
        self.groupBox_42.setObjectName("groupBox_42")
        self.lineEdit_Check_DrainageLineTouchDrainageLine = QtWidgets.QLineEdit(self.groupBox_42)
        self.lineEdit_Check_DrainageLineTouchDrainageLine.setGeometry(QtCore.QRect(10, 20, 81, 20))
        self.lineEdit_Check_DrainageLineTouchDrainageLine.setObjectName("lineEdit_Check_DrainageLineTouchDrainageLine")
        self.label_48 = QtWidgets.QLabel(self.groupBox_42)
        self.label_48.setGeometry(QtCore.QRect(10, 40, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_48.setFont(font)
        self.label_48.setObjectName("label_48")
        self.pushButton_BreakDrainageLines = QtWidgets.QPushButton(self.groupBox_39)
        self.pushButton_BreakDrainageLines.setEnabled(False)
        self.pushButton_BreakDrainageLines.setGeometry(QtCore.QRect(60, 190, 75, 23))
        self.pushButton_BreakDrainageLines.setObjectName("pushButton_BreakDrainageLines")
        self.tabWidget.addTab(self.tab2, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.groupBox_12 = QtWidgets.QGroupBox(self.tab_8)
        self.groupBox_12.setGeometry(QtCore.QRect(10, 10, 231, 341))
        self.groupBox_12.setObjectName("groupBox_12")
        self.groupBox_14 = QtWidgets.QGroupBox(self.groupBox_12)
        self.groupBox_14.setGeometry(QtCore.QRect(10, 50, 211, 61))
        self.groupBox_14.setObjectName("groupBox_14")
        self.lineEdit_Check_PointValenceValue2 = QtWidgets.QLineEdit(self.groupBox_14)
        self.lineEdit_Check_PointValenceValue2.setGeometry(QtCore.QRect(10, 20, 81, 20))
        self.lineEdit_Check_PointValenceValue2.setObjectName("lineEdit_Check_PointValenceValue2")
        self.pushButton_UnionDrainageLineValence2 = QtWidgets.QPushButton(self.groupBox_14)
        self.pushButton_UnionDrainageLineValence2.setEnabled(False)
        self.pushButton_UnionDrainageLineValence2.setGeometry(QtCore.QRect(100, 20, 91, 23))
        self.pushButton_UnionDrainageLineValence2.setObjectName("pushButton_UnionDrainageLineValence2")
        self.label_49 = QtWidgets.QLabel(self.groupBox_14)
        self.label_49.setGeometry(QtCore.QRect(10, 40, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_49.setFont(font)
        self.label_49.setObjectName("label_49")
        self.groupBox_15 = QtWidgets.QGroupBox(self.groupBox_12)
        self.groupBox_15.setGeometry(QtCore.QRect(10, 120, 211, 61))
        self.groupBox_15.setObjectName("groupBox_15")
        self.lineEdit_Check_PointValenceValue4 = QtWidgets.QLineEdit(self.groupBox_15)
        self.lineEdit_Check_PointValenceValue4.setGeometry(QtCore.QRect(10, 20, 81, 20))
        self.lineEdit_Check_PointValenceValue4.setObjectName("lineEdit_Check_PointValenceValue4")
        self.label_30 = QtWidgets.QLabel(self.groupBox_15)
        self.label_30.setGeometry(QtCore.QRect(100, 20, 81, 16))
        self.label_30.setObjectName("label_30")
        self.label_50 = QtWidgets.QLabel(self.groupBox_15)
        self.label_50.setGeometry(QtCore.QRect(10, 40, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_50.setFont(font)
        self.label_50.setObjectName("label_50")
        self.pushButton_Execute_Network_Topology = QtWidgets.QPushButton(self.groupBox_12)
        self.pushButton_Execute_Network_Topology.setGeometry(QtCore.QRect(70, 20, 75, 23))
        self.pushButton_Execute_Network_Topology.setObjectName("pushButton_Execute_Network_Topology")
        self.label_29 = QtWidgets.QLabel(self.groupBox_12)
        self.label_29.setGeometry(QtCore.QRect(30, 200, 91, 20))
        self.label_29.setObjectName("label_29")
        self.lineEdit_DrainagePointOffset = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEdit_DrainagePointOffset.setGeometry(QtCore.QRect(130, 200, 81, 20))
        self.lineEdit_DrainagePointOffset.setObjectName("lineEdit_DrainagePointOffset")
        self.groupBox_13 = QtWidgets.QGroupBox(self.tab_8)
        self.groupBox_13.setGeometry(QtCore.QRect(250, 10, 191, 341))
        self.groupBox_13.setObjectName("groupBox_13")
        self.pushButton_UpdateShorelineStartingPoint = QtWidgets.QPushButton(self.groupBox_13)
        self.pushButton_UpdateShorelineStartingPoint.setGeometry(QtCore.QRect(60, 50, 121, 23))
        self.pushButton_UpdateShorelineStartingPoint.setObjectName("pushButton_UpdateShorelineStartingPoint")
        self.pushButton_UpdateShorelineEndingPoint = QtWidgets.QPushButton(self.groupBox_13)
        self.pushButton_UpdateShorelineEndingPoint.setGeometry(QtCore.QRect(60, 20, 121, 23))
        self.pushButton_UpdateShorelineEndingPoint.setObjectName("pushButton_UpdateShorelineEndingPoint")
        self.lineEdit_UpdateShorelineEndingPoint = QtWidgets.QLineEdit(self.groupBox_13)
        self.lineEdit_UpdateShorelineEndingPoint.setGeometry(QtCore.QRect(10, 20, 41, 20))
        self.lineEdit_UpdateShorelineEndingPoint.setObjectName("lineEdit_UpdateShorelineEndingPoint")
        self.lineEdit_UpdateShorelineStartingPoint = QtWidgets.QLineEdit(self.groupBox_13)
        self.lineEdit_UpdateShorelineStartingPoint.setGeometry(QtCore.QRect(10, 50, 41, 20))
        self.lineEdit_UpdateShorelineStartingPoint.setObjectName("lineEdit_UpdateShorelineStartingPoint")
        self.label_40 = QtWidgets.QLabel(self.groupBox_13)
        self.label_40.setGeometry(QtCore.QRect(10, 80, 161, 16))
        self.label_40.setObjectName("label_40")
        self.groupBox_16 = QtWidgets.QGroupBox(self.tab_8)
        self.groupBox_16.setGeometry(QtCore.QRect(450, 10, 201, 341))
        self.groupBox_16.setObjectName("groupBox_16")
        self.groupBox_17 = QtWidgets.QGroupBox(self.groupBox_16)
        self.groupBox_17.setGeometry(QtCore.QRect(10, 50, 181, 61))
        self.groupBox_17.setObjectName("groupBox_17")
        self.lineEdit_Check_DrainageLineIsDisconnected = QtWidgets.QLineEdit(self.groupBox_17)
        self.lineEdit_Check_DrainageLineIsDisconnected.setGeometry(QtCore.QRect(10, 20, 71, 20))
        self.lineEdit_Check_DrainageLineIsDisconnected.setObjectName("lineEdit_Check_DrainageLineIsDisconnected")
        self.label_31 = QtWidgets.QLabel(self.groupBox_17)
        self.label_31.setGeometry(QtCore.QRect(90, 20, 81, 16))
        self.label_31.setObjectName("label_31")
        self.label_51 = QtWidgets.QLabel(self.groupBox_17)
        self.label_51.setGeometry(QtCore.QRect(10, 40, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_51.setFont(font)
        self.label_51.setObjectName("label_51")
        self.groupBox_18 = QtWidgets.QGroupBox(self.groupBox_16)
        self.groupBox_18.setGeometry(QtCore.QRect(10, 110, 181, 61))
        self.groupBox_18.setObjectName("groupBox_18")
        self.lineEdit_Check_PointDivergent = QtWidgets.QLineEdit(self.groupBox_18)
        self.lineEdit_Check_PointDivergent.setGeometry(QtCore.QRect(10, 20, 71, 20))
        self.lineEdit_Check_PointDivergent.setObjectName("lineEdit_Check_PointDivergent")
        self.label_32 = QtWidgets.QLabel(self.groupBox_18)
        self.label_32.setGeometry(QtCore.QRect(90, 20, 81, 16))
        self.label_32.setObjectName("label_32")
        self.label_52 = QtWidgets.QLabel(self.groupBox_18)
        self.label_52.setGeometry(QtCore.QRect(10, 40, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_52.setFont(font)
        self.label_52.setObjectName("label_52")
        self.pushButton_Check_Execute_Flow_Direction = QtWidgets.QPushButton(self.groupBox_16)
        self.pushButton_Check_Execute_Flow_Direction.setGeometry(QtCore.QRect(60, 20, 75, 23))
        self.pushButton_Check_Execute_Flow_Direction.setObjectName("pushButton_Check_Execute_Flow_Direction")
        self.tabWidget.addTab(self.tab_8, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.groupBox_19 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_19.setGeometry(QtCore.QRect(220, 10, 201, 341))
        self.groupBox_19.setObjectName("groupBox_19")
        self.groupBox_23 = QtWidgets.QGroupBox(self.groupBox_19)
        self.groupBox_23.setGeometry(QtCore.QRect(10, 110, 181, 61))
        self.groupBox_23.setObjectName("groupBox_23")
        self.lineEdit_Check_DrainageAreaOverlapDrainageArea = QtWidgets.QLineEdit(self.groupBox_23)
        self.lineEdit_Check_DrainageAreaOverlapDrainageArea.setGeometry(QtCore.QRect(10, 20, 81, 20))
        self.lineEdit_Check_DrainageAreaOverlapDrainageArea.setObjectName("lineEdit_Check_DrainageAreaOverlapDrainageArea")
        self.pushButton_RemoveDrainageAreaOverlap = QtWidgets.QPushButton(self.groupBox_23)
        self.pushButton_RemoveDrainageAreaOverlap.setEnabled(False)
        self.pushButton_RemoveDrainageAreaOverlap.setGeometry(QtCore.QRect(100, 20, 75, 23))
        self.pushButton_RemoveDrainageAreaOverlap.setObjectName("pushButton_RemoveDrainageAreaOverlap")
        self.label_57 = QtWidgets.QLabel(self.groupBox_23)
        self.label_57.setGeometry(QtCore.QRect(10, 40, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_57.setFont(font)
        self.label_57.setObjectName("label_57")
        self.groupBox_24 = QtWidgets.QGroupBox(self.groupBox_19)
        self.groupBox_24.setGeometry(QtCore.QRect(10, 50, 181, 61))
        self.groupBox_24.setObjectName("groupBox_24")
        self.lineEdit_Check_DrainageAreaWithinDrainageArea = QtWidgets.QLineEdit(self.groupBox_24)
        self.lineEdit_Check_DrainageAreaWithinDrainageArea.setGeometry(QtCore.QRect(10, 20, 81, 20))
        self.lineEdit_Check_DrainageAreaWithinDrainageArea.setObjectName("lineEdit_Check_DrainageAreaWithinDrainageArea")
        self.pushButton_DeleteDrainageAreaWithinDrainageArea = QtWidgets.QPushButton(self.groupBox_24)
        self.pushButton_DeleteDrainageAreaWithinDrainageArea.setEnabled(False)
        self.pushButton_DeleteDrainageAreaWithinDrainageArea.setGeometry(QtCore.QRect(100, 20, 75, 23))
        self.pushButton_DeleteDrainageAreaWithinDrainageArea.setObjectName("pushButton_DeleteDrainageAreaWithinDrainageArea")
        self.label_56 = QtWidgets.QLabel(self.groupBox_24)
        self.label_56.setGeometry(QtCore.QRect(10, 40, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_56.setFont(font)
        self.label_56.setObjectName("label_56")
        self.pushButton_Check_DrainageAreaTopologyConsistencies = QtWidgets.QPushButton(self.groupBox_19)
        self.pushButton_Check_DrainageAreaTopologyConsistencies.setGeometry(QtCore.QRect(60, 20, 75, 23))
        self.pushButton_Check_DrainageAreaTopologyConsistencies.setObjectName("pushButton_Check_DrainageAreaTopologyConsistencies")
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_10.setGeometry(QtCore.QRect(10, 10, 201, 341))
        self.groupBox_10.setObjectName("groupBox_10")
        self.groupBox_44 = QtWidgets.QGroupBox(self.groupBox_10)
        self.groupBox_44.setGeometry(QtCore.QRect(10, 150, 181, 61))
        self.groupBox_44.setObjectName("groupBox_44")
        self.pushButton_MakeDrainageAreaSimple = QtWidgets.QPushButton(self.groupBox_44)
        self.pushButton_MakeDrainageAreaSimple.setEnabled(False)
        self.pushButton_MakeDrainageAreaSimple.setGeometry(QtCore.QRect(100, 20, 75, 23))
        self.pushButton_MakeDrainageAreaSimple.setObjectName("pushButton_MakeDrainageAreaSimple")
        self.lineEdit_Check_DrainageAreaIsNotSimple = QtWidgets.QLineEdit(self.groupBox_44)
        self.lineEdit_Check_DrainageAreaIsNotSimple.setGeometry(QtCore.QRect(10, 20, 81, 20))
        self.lineEdit_Check_DrainageAreaIsNotSimple.setObjectName("lineEdit_Check_DrainageAreaIsNotSimple")
        self.label_53 = QtWidgets.QLabel(self.groupBox_44)
        self.label_53.setGeometry(QtCore.QRect(10, 40, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_53.setFont(font)
        self.label_53.setObjectName("label_53")
        self.groupBox_45 = QtWidgets.QGroupBox(self.groupBox_10)
        self.groupBox_45.setGeometry(QtCore.QRect(10, 220, 181, 61))
        self.groupBox_45.setObjectName("groupBox_45")
        self.pushButton_MakeDrainageAreaValid = QtWidgets.QPushButton(self.groupBox_45)
        self.pushButton_MakeDrainageAreaValid.setEnabled(False)
        self.pushButton_MakeDrainageAreaValid.setGeometry(QtCore.QRect(100, 20, 75, 23))
        self.pushButton_MakeDrainageAreaValid.setObjectName("pushButton_MakeDrainageAreaValid")
        self.lineEdit_Check_DrainageAreaIsNotValid = QtWidgets.QLineEdit(self.groupBox_45)
        self.lineEdit_Check_DrainageAreaIsNotValid.setGeometry(QtCore.QRect(10, 20, 81, 20))
        self.lineEdit_Check_DrainageAreaIsNotValid.setObjectName("lineEdit_Check_DrainageAreaIsNotValid")
        self.label_54 = QtWidgets.QLabel(self.groupBox_45)
        self.label_54.setGeometry(QtCore.QRect(10, 40, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_54.setFont(font)
        self.label_54.setObjectName("label_54")
        self.lineEdit_DrainageAreaPrecision = QtWidgets.QLineEdit(self.groupBox_10)
        self.lineEdit_DrainageAreaPrecision.setGeometry(QtCore.QRect(100, 20, 81, 20))
        self.lineEdit_DrainageAreaPrecision.setObjectName("lineEdit_DrainageAreaPrecision")
        self.label_33 = QtWidgets.QLabel(self.groupBox_10)
        self.label_33.setGeometry(QtCore.QRect(20, 20, 81, 16))
        self.label_33.setObjectName("label_33")
        self.lineEdit_DrainageAreaOffset = QtWidgets.QLineEdit(self.groupBox_10)
        self.lineEdit_DrainageAreaOffset.setGeometry(QtCore.QRect(110, 300, 81, 20))
        self.lineEdit_DrainageAreaOffset.setObjectName("lineEdit_DrainageAreaOffset")
        self.label_34 = QtWidgets.QLabel(self.groupBox_10)
        self.label_34.setGeometry(QtCore.QRect(20, 300, 81, 16))
        self.label_34.setObjectName("label_34")
        self.pushButton_Check_DrainageAreaGeometryConsistencies = QtWidgets.QPushButton(self.groupBox_10)
        self.pushButton_Check_DrainageAreaGeometryConsistencies.setGeometry(QtCore.QRect(60, 50, 75, 23))
        self.pushButton_Check_DrainageAreaGeometryConsistencies.setObjectName("pushButton_Check_DrainageAreaGeometryConsistencies")
        self.groupBox_43 = QtWidgets.QGroupBox(self.groupBox_10)
        self.groupBox_43.setGeometry(QtCore.QRect(10, 80, 181, 61))
        self.groupBox_43.setObjectName("groupBox_43")
        self.pushButton_ExplodeDrainageArea = QtWidgets.QPushButton(self.groupBox_43)
        self.pushButton_ExplodeDrainageArea.setEnabled(False)
        self.pushButton_ExplodeDrainageArea.setGeometry(QtCore.QRect(100, 20, 75, 23))
        self.pushButton_ExplodeDrainageArea.setObjectName("pushButton_ExplodeDrainageArea")
        self.lineEdit_Check_DrainageAreaIsNotSingle = QtWidgets.QLineEdit(self.groupBox_43)
        self.lineEdit_Check_DrainageAreaIsNotSingle.setGeometry(QtCore.QRect(10, 20, 81, 20))
        self.lineEdit_Check_DrainageAreaIsNotSingle.setObjectName("lineEdit_Check_DrainageAreaIsNotSingle")
        self.label_55 = QtWidgets.QLabel(self.groupBox_43)
        self.label_55.setGeometry(QtCore.QRect(10, 40, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_55.setFont(font)
        self.label_55.setObjectName("label_55")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox_25 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_25.setGeometry(QtCore.QRect(10, 10, 221, 341))
        self.groupBox_25.setObjectName("groupBox_25")
        self.groupBox_27 = QtWidgets.QGroupBox(self.groupBox_25)
        self.groupBox_27.setGeometry(QtCore.QRect(10, 120, 201, 61))
        self.groupBox_27.setObjectName("groupBox_27")
        self.lineEdit_Check_DrainageLineNoDrainageArea = QtWidgets.QLineEdit(self.groupBox_27)
        self.lineEdit_Check_DrainageLineNoDrainageArea.setGeometry(QtCore.QRect(10, 20, 81, 20))
        self.lineEdit_Check_DrainageLineNoDrainageArea.setObjectName("lineEdit_Check_DrainageLineNoDrainageArea")
        self.label_35 = QtWidgets.QLabel(self.groupBox_27)
        self.label_35.setGeometry(QtCore.QRect(100, 20, 81, 16))
        self.label_35.setObjectName("label_35")
        self.label_58 = QtWidgets.QLabel(self.groupBox_27)
        self.label_58.setGeometry(QtCore.QRect(10, 40, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_58.setFont(font)
        self.label_58.setObjectName("label_58")
        self.groupBox_28 = QtWidgets.QGroupBox(self.groupBox_25)
        self.groupBox_28.setGeometry(QtCore.QRect(10, 50, 201, 61))
        self.groupBox_28.setObjectName("groupBox_28")
        self.lineEdit_Check_DrainageAreaMoreOneDrainageLine = QtWidgets.QLineEdit(self.groupBox_28)
        self.lineEdit_Check_DrainageAreaMoreOneDrainageLine.setGeometry(QtCore.QRect(10, 20, 81, 20))
        self.lineEdit_Check_DrainageAreaMoreOneDrainageLine.setObjectName("lineEdit_Check_DrainageAreaMoreOneDrainageLine")
        self.label_36 = QtWidgets.QLabel(self.groupBox_28)
        self.label_36.setGeometry(QtCore.QRect(100, 20, 81, 16))
        self.label_36.setObjectName("label_36")
        self.label_59 = QtWidgets.QLabel(self.groupBox_28)
        self.label_59.setGeometry(QtCore.QRect(10, 40, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_59.setFont(font)
        self.label_59.setObjectName("label_59")
        self.groupBox_29 = QtWidgets.QGroupBox(self.groupBox_25)
        self.groupBox_29.setGeometry(QtCore.QRect(10, 260, 201, 61))
        self.groupBox_29.setObjectName("groupBox_29")
        self.lineEdit_Check_DrainageLineMoreOneDrainageArea = QtWidgets.QLineEdit(self.groupBox_29)
        self.lineEdit_Check_DrainageLineMoreOneDrainageArea.setGeometry(QtCore.QRect(10, 20, 81, 20))
        self.lineEdit_Check_DrainageLineMoreOneDrainageArea.setObjectName("lineEdit_Check_DrainageLineMoreOneDrainageArea")
        self.label_37 = QtWidgets.QLabel(self.groupBox_29)
        self.label_37.setGeometry(QtCore.QRect(100, 20, 81, 16))
        self.label_37.setObjectName("label_37")
        self.label_60 = QtWidgets.QLabel(self.groupBox_29)
        self.label_60.setGeometry(QtCore.QRect(10, 40, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_60.setFont(font)
        self.label_60.setObjectName("label_60")
        self.pushButton_Check_DrainageAreaDrainageLineConsistencies = QtWidgets.QPushButton(self.groupBox_25)
        self.pushButton_Check_DrainageAreaDrainageLineConsistencies.setGeometry(QtCore.QRect(60, 20, 75, 23))
        self.pushButton_Check_DrainageAreaDrainageLineConsistencies.setObjectName("pushButton_Check_DrainageAreaDrainageLineConsistencies")
        self.groupBox_26 = QtWidgets.QGroupBox(self.groupBox_25)
        self.groupBox_26.setGeometry(QtCore.QRect(10, 190, 201, 61))
        self.groupBox_26.setObjectName("groupBox_26")
        self.lineEdit_Check_DrainageAreaNoDrainageLine = QtWidgets.QLineEdit(self.groupBox_26)
        self.lineEdit_Check_DrainageAreaNoDrainageLine.setGeometry(QtCore.QRect(10, 20, 81, 20))
        self.lineEdit_Check_DrainageAreaNoDrainageLine.setObjectName("lineEdit_Check_DrainageAreaNoDrainageLine")
        self.pushButton_Union_DrainageAreaNoDrainageLine = QtWidgets.QPushButton(self.groupBox_26)
        self.pushButton_Union_DrainageAreaNoDrainageLine.setEnabled(False)
        self.pushButton_Union_DrainageAreaNoDrainageLine.setGeometry(QtCore.QRect(100, 20, 75, 23))
        self.pushButton_Union_DrainageAreaNoDrainageLine.setObjectName("pushButton_Union_DrainageAreaNoDrainageLine")
        self.label_61 = QtWidgets.QLabel(self.groupBox_26)
        self.label_61.setGeometry(QtCore.QRect(10, 40, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_61.setFont(font)
        self.label_61.setObjectName("label_61")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_31 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_31.setGeometry(QtCore.QRect(10, 10, 641, 341))
        self.groupBox_31.setObjectName("groupBox_31")
        self.groupBox_32 = QtWidgets.QGroupBox(self.groupBox_31)
        self.groupBox_32.setGeometry(QtCore.QRect(10, 20, 621, 311))
        self.groupBox_32.setObjectName("groupBox_32")
        self.pushButton_Principal_Procedure = QtWidgets.QPushButton(self.groupBox_32)
        self.pushButton_Principal_Procedure.setGeometry(QtCore.QRect(510, 280, 101, 23))
        self.pushButton_Principal_Procedure.setObjectName("pushButton_Principal_Procedure")
        self.checkBox_CalculateDrainageLineLength = QtWidgets.QCheckBox(self.groupBox_32)
        self.checkBox_CalculateDrainageLineLength.setGeometry(QtCore.QRect(10, 20, 221, 17))
        self.checkBox_CalculateDrainageLineLength.setAcceptDrops(False)
        self.checkBox_CalculateDrainageLineLength.setAutoFillBackground(False)
        self.checkBox_CalculateDrainageLineLength.setChecked(True)
        self.checkBox_CalculateDrainageLineLength.setObjectName("checkBox_CalculateDrainageLineLength")
        self.checkBox_CalculateDrainageAreaArea = QtWidgets.QCheckBox(self.groupBox_32)
        self.checkBox_CalculateDrainageAreaArea.setGeometry(QtCore.QRect(10, 40, 231, 17))
        self.checkBox_CalculateDrainageAreaArea.setChecked(True)
        self.checkBox_CalculateDrainageAreaArea.setObjectName("checkBox_CalculateDrainageAreaArea")
        self.checkBox_CalculateDistanceToSea = QtWidgets.QCheckBox(self.groupBox_32)
        self.checkBox_CalculateDistanceToSea.setGeometry(QtCore.QRect(10, 60, 211, 17))
        self.checkBox_CalculateDistanceToSea.setChecked(True)
        self.checkBox_CalculateDistanceToSea.setObjectName("checkBox_CalculateDistanceToSea")
        self.checkBox_CalculateUpstreamArea = QtWidgets.QCheckBox(self.groupBox_32)
        self.checkBox_CalculateUpstreamArea.setGeometry(QtCore.QRect(10, 80, 151, 17))
        self.checkBox_CalculateUpstreamArea.setChecked(True)
        self.checkBox_CalculateUpstreamArea.setObjectName("checkBox_CalculateUpstreamArea")
        self.checkBox_CalculateUpstreamDrainageLine = QtWidgets.QCheckBox(self.groupBox_32)
        self.checkBox_CalculateUpstreamDrainageLine.setGeometry(QtCore.QRect(10, 100, 171, 17))
        self.checkBox_CalculateUpstreamDrainageLine.setChecked(True)
        self.checkBox_CalculateUpstreamDrainageLine.setObjectName("checkBox_CalculateUpstreamDrainageLine")
        self.checkBox_CalculateDownstreamDrainageLine = QtWidgets.QCheckBox(self.groupBox_32)
        self.checkBox_CalculateDownstreamDrainageLine.setGeometry(QtCore.QRect(10, 120, 221, 17))
        self.checkBox_CalculateDownstreamDrainageLine.setChecked(True)
        self.checkBox_CalculateDownstreamDrainageLine.setObjectName("checkBox_CalculateDownstreamDrainageLine")
        self.checkBox_Calculate_Pfafstetter_Codification = QtWidgets.QCheckBox(self.groupBox_32)
        self.checkBox_Calculate_Pfafstetter_Codification.setGeometry(QtCore.QRect(10, 140, 211, 17))
        self.checkBox_Calculate_Pfafstetter_Codification.setChecked(True)
        self.checkBox_Calculate_Pfafstetter_Codification.setObjectName("checkBox_Calculate_Pfafstetter_Codification")
        self.checkBox_UpdatePfafstetterBasinCode = QtWidgets.QCheckBox(self.groupBox_32)
        self.checkBox_UpdatePfafstetterBasinCode.setGeometry(QtCore.QRect(10, 160, 281, 17))
        self.checkBox_UpdatePfafstetterBasinCode.setChecked(True)
        self.checkBox_UpdatePfafstetterBasinCode.setObjectName("checkBox_UpdatePfafstetterBasinCode")
        self.checkBox_UpdateWatercourse = QtWidgets.QCheckBox(self.groupBox_32)
        self.checkBox_UpdateWatercourse.setGeometry(QtCore.QRect(10, 200, 151, 17))
        self.checkBox_UpdateWatercourse.setChecked(True)
        self.checkBox_UpdateWatercourse.setObjectName("checkBox_UpdateWatercourse")
        self.checkBox_UpdateWatercourse_Point = QtWidgets.QCheckBox(self.groupBox_32)
        self.checkBox_UpdateWatercourse_Point.setGeometry(QtCore.QRect(10, 240, 201, 17))
        self.checkBox_UpdateWatercourse_Point.setChecked(True)
        self.checkBox_UpdateWatercourse_Point.setObjectName("checkBox_UpdateWatercourse_Point")
        self.checkBox_calculatestrahlernumber = QtWidgets.QCheckBox(self.groupBox_32)
        self.checkBox_calculatestrahlernumber.setGeometry(QtCore.QRect(10, 260, 151, 17))
        self.checkBox_calculatestrahlernumber.setChecked(True)
        self.checkBox_calculatestrahlernumber.setObjectName("checkBox_calculatestrahlernumber")
        self.lineEdit_srid_drainage_line_length = QtWidgets.QLineEdit(self.groupBox_32)
        self.lineEdit_srid_drainage_line_length.setGeometry(QtCore.QRect(240, 20, 71, 20))
        self.lineEdit_srid_drainage_line_length.setObjectName("lineEdit_srid_drainage_line_length")
        self.lineEdit_srid_drainage_area_area = QtWidgets.QLineEdit(self.groupBox_32)
        self.lineEdit_srid_drainage_area_area.setGeometry(QtCore.QRect(240, 40, 71, 20))
        self.lineEdit_srid_drainage_area_area.setObjectName("lineEdit_srid_drainage_area_area")
        self.label_21 = QtWidgets.QLabel(self.groupBox_32)
        self.label_21.setGeometry(QtCore.QRect(210, 20, 31, 16))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.groupBox_32)
        self.label_22.setGeometry(QtCore.QRect(210, 40, 31, 16))
        self.label_22.setObjectName("label_22")
        self.lineEdit_factor_drainage_line_length = QtWidgets.QLineEdit(self.groupBox_32)
        self.lineEdit_factor_drainage_line_length.setGeometry(QtCore.QRect(360, 20, 51, 20))
        self.lineEdit_factor_drainage_line_length.setObjectName("lineEdit_factor_drainage_line_length")
        self.lineEdit_factor_drainage_area_area = QtWidgets.QLineEdit(self.groupBox_32)
        self.lineEdit_factor_drainage_area_area.setGeometry(QtCore.QRect(360, 40, 51, 20))
        self.lineEdit_factor_drainage_area_area.setObjectName("lineEdit_factor_drainage_area_area")
        self.label_23 = QtWidgets.QLabel(self.groupBox_32)
        self.label_23.setGeometry(QtCore.QRect(320, 20, 41, 20))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.groupBox_32)
        self.label_24.setGeometry(QtCore.QRect(320, 40, 41, 20))
        self.label_24.setObjectName("label_24")
        self.lineEdit_distance_to_sea = QtWidgets.QLineEdit(self.groupBox_32)
        self.lineEdit_distance_to_sea.setGeometry(QtCore.QRect(200, 60, 51, 20))
        self.lineEdit_distance_to_sea.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_distance_to_sea.setObjectName("lineEdit_distance_to_sea")
        self.lineEdit_pfafstetter_basin_code = QtWidgets.QLineEdit(self.groupBox_32)
        self.lineEdit_pfafstetter_basin_code.setGeometry(QtCore.QRect(220, 160, 61, 20))
        self.lineEdit_pfafstetter_basin_code.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_pfafstetter_basin_code.setObjectName("lineEdit_pfafstetter_basin_code")
        self.checkBox_UpdatePfafstetterWatercourseCode = QtWidgets.QCheckBox(self.groupBox_32)
        self.checkBox_UpdatePfafstetterWatercourseCode.setGeometry(QtCore.QRect(10, 180, 301, 17))
        self.checkBox_UpdatePfafstetterWatercourseCode.setChecked(True)
        self.checkBox_UpdatePfafstetterWatercourseCode.setObjectName("checkBox_UpdatePfafstetterWatercourseCode")
        self.checkBox_InsertColumnPfafstetterBasinCodeLevel = QtWidgets.QCheckBox(self.groupBox_32)
        self.checkBox_InsertColumnPfafstetterBasinCodeLevel.setEnabled(True)
        self.checkBox_InsertColumnPfafstetterBasinCodeLevel.setGeometry(QtCore.QRect(10, 220, 331, 17))
        self.checkBox_InsertColumnPfafstetterBasinCodeLevel.setChecked(False)
        self.checkBox_InsertColumnPfafstetterBasinCodeLevel.setObjectName("checkBox_InsertColumnPfafstetterBasinCodeLevel")
        self.checkBox_updateshoreline = QtWidgets.QCheckBox(self.groupBox_32)
        self.checkBox_updateshoreline.setGeometry(QtCore.QRect(10, 280, 231, 17))
        self.checkBox_updateshoreline.setChecked(True)
        self.checkBox_updateshoreline.setObjectName("checkBox_updateshoreline")
        self.checkBox_TurnOnKeysIndex = QtWidgets.QCheckBox(self.groupBox_32)
        self.checkBox_TurnOnKeysIndex.setGeometry(QtCore.QRect(430, 40, 171, 17))
        self.checkBox_TurnOnKeysIndex.setChecked(True)
        self.checkBox_TurnOnKeysIndex.setObjectName("checkBox_TurnOnKeysIndex")
        self.checkBox_UpdateDomainColumn = QtWidgets.QCheckBox(self.groupBox_32)
        self.checkBox_UpdateDomainColumn.setGeometry(QtCore.QRect(430, 60, 181, 20))
        self.checkBox_UpdateDomainColumn.setChecked(False)
        self.checkBox_UpdateDomainColumn.setObjectName("checkBox_UpdateDomainColumn")
        self.checkBox_UpdateWatershed = QtWidgets.QCheckBox(self.groupBox_32)
        self.checkBox_UpdateWatershed.setGeometry(QtCore.QRect(430, 80, 171, 17))
        self.checkBox_UpdateWatershed.setChecked(False)
        self.checkBox_UpdateWatershed.setObjectName("checkBox_UpdateWatershed")
        self.lineEdit_watershed_pfafstetter_max_code = QtWidgets.QLineEdit(self.groupBox_32)
        self.lineEdit_watershed_pfafstetter_max_code.setGeometry(QtCore.QRect(570, 80, 21, 20))
        self.lineEdit_watershed_pfafstetter_max_code.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_watershed_pfafstetter_max_code.setObjectName("lineEdit_watershed_pfafstetter_max_code")
        self.checkBox_TurnOffKeysIndex = QtWidgets.QCheckBox(self.groupBox_32)
        self.checkBox_TurnOffKeysIndex.setGeometry(QtCore.QRect(430, 20, 171, 17))
        self.checkBox_TurnOffKeysIndex.setChecked(True)
        self.checkBox_TurnOffKeysIndex.setObjectName("checkBox_TurnOffKeysIndex")
        self.checkBox_Vacuum_Database = QtWidgets.QCheckBox(self.groupBox_32)
        self.checkBox_Vacuum_Database.setGeometry(QtCore.QRect(430, 100, 171, 17))
        self.checkBox_Vacuum_Database.setChecked(False)
        self.checkBox_Vacuum_Database.setObjectName("checkBox_Vacuum_Database")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.groupBox_30 = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox_30.setGeometry(QtCore.QRect(10, 10, 201, 51))
        self.groupBox_30.setObjectName("groupBox_30")
        self.pushButton_UpdateExportTables = QtWidgets.QPushButton(self.groupBox_30)
        self.pushButton_UpdateExportTables.setGeometry(QtCore.QRect(50, 20, 91, 21))
        self.pushButton_UpdateExportTables.setObjectName("pushButton_UpdateExportTables")
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.groupBox_47 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_47.setGeometry(QtCore.QRect(10, 10, 641, 341))
        self.groupBox_47.setObjectName("groupBox_47")
        self.groupBox_52 = QtWidgets.QGroupBox(self.groupBox_47)
        self.groupBox_52.setGeometry(QtCore.QRect(430, 20, 201, 51))
        self.groupBox_52.setObjectName("groupBox_52")
        self.pushButton_Stop_Systematize_Hydronym = QtWidgets.QPushButton(self.groupBox_52)
        self.pushButton_Stop_Systematize_Hydronym.setGeometry(QtCore.QRect(50, 20, 75, 23))
        self.pushButton_Stop_Systematize_Hydronym.setObjectName("pushButton_Stop_Systematize_Hydronym")
        self.groupBox_34 = QtWidgets.QGroupBox(self.groupBox_47)
        self.groupBox_34.setGeometry(QtCore.QRect(220, 20, 201, 201))
        self.groupBox_34.setObjectName("groupBox_34")
        self.groupBox_51 = QtWidgets.QGroupBox(self.groupBox_34)
        self.groupBox_51.setGeometry(QtCore.QRect(10, 140, 181, 51))
        self.groupBox_51.setObjectName("groupBox_51")
        self.pushButton_Update_OriginalHydronym = QtWidgets.QPushButton(self.groupBox_51)
        self.pushButton_Update_OriginalHydronym.setGeometry(QtCore.QRect(60, 20, 75, 23))
        self.pushButton_Update_OriginalHydronym.setObjectName("pushButton_Update_OriginalHydronym")
        self.groupBox_59 = QtWidgets.QGroupBox(self.groupBox_34)
        self.groupBox_59.setGeometry(QtCore.QRect(10, 80, 181, 51))
        self.groupBox_59.setObjectName("groupBox_59")
        self.label_39 = QtWidgets.QLabel(self.groupBox_59)
        self.label_39.setGeometry(QtCore.QRect(40, 20, 131, 16))
        self.label_39.setObjectName("label_39")
        self.groupBox_60 = QtWidgets.QGroupBox(self.groupBox_34)
        self.groupBox_60.setGeometry(QtCore.QRect(10, 20, 181, 51))
        self.groupBox_60.setObjectName("groupBox_60")
        self.pushButton_Systematize_Hydronym = QtWidgets.QPushButton(self.groupBox_60)
        self.pushButton_Systematize_Hydronym.setGeometry(QtCore.QRect(60, 20, 75, 23))
        self.pushButton_Systematize_Hydronym.setObjectName("pushButton_Systematize_Hydronym")
        self.groupBox_58 = QtWidgets.QGroupBox(self.groupBox_47)
        self.groupBox_58.setGeometry(QtCore.QRect(10, 20, 201, 51))
        self.groupBox_58.setObjectName("groupBox_58")
        self.pushButton_Start_Systematize_Hydronym = QtWidgets.QPushButton(self.groupBox_58)
        self.pushButton_Start_Systematize_Hydronym.setGeometry(QtCore.QRect(60, 20, 75, 23))
        self.pushButton_Start_Systematize_Hydronym.setObjectName("pushButton_Start_Systematize_Hydronym")
        self.groupBox_50 = QtWidgets.QGroupBox(self.groupBox_47)
        self.groupBox_50.setGeometry(QtCore.QRect(220, 230, 211, 91))
        self.groupBox_50.setObjectName("groupBox_50")
        self.pushButton_Check_ConfluenceHydronym = QtWidgets.QPushButton(self.groupBox_50)
        self.pushButton_Check_ConfluenceHydronym.setGeometry(QtCore.QRect(60, 20, 75, 23))
        self.pushButton_Check_ConfluenceHydronym.setObjectName("pushButton_Check_ConfluenceHydronym")
        self.lineEdit_ConfluenceHydronym = QtWidgets.QLineEdit(self.groupBox_50)
        self.lineEdit_ConfluenceHydronym.setGeometry(QtCore.QRect(10, 50, 81, 20))
        self.lineEdit_ConfluenceHydronym.setObjectName("lineEdit_ConfluenceHydronym")
        self.label_38 = QtWidgets.QLabel(self.groupBox_50)
        self.label_38.setGeometry(QtCore.QRect(90, 40, 111, 31))
        self.label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_38.setObjectName("label_38")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.groupBox_53 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_53.setGeometry(QtCore.QRect(10, 10, 641, 341))
        self.groupBox_53.setObjectName("groupBox_53")
        self.groupBox_54 = QtWidgets.QGroupBox(self.groupBox_53)
        self.groupBox_54.setGeometry(QtCore.QRect(430, 20, 171, 111))
        self.groupBox_54.setObjectName("groupBox_54")
        self.pushButton_turn_off_audit = QtWidgets.QPushButton(self.groupBox_54)
        self.pushButton_turn_off_audit.setGeometry(QtCore.QRect(90, 20, 75, 23))
        self.pushButton_turn_off_audit.setObjectName("pushButton_turn_off_audit")
        self.pushButton_turn_on_audit = QtWidgets.QPushButton(self.groupBox_54)
        self.pushButton_turn_on_audit.setGeometry(QtCore.QRect(10, 20, 75, 23))
        self.pushButton_turn_on_audit.setObjectName("pushButton_turn_on_audit")
        self.pushButton_reset_drainage_line_audit = QtWidgets.QPushButton(self.groupBox_54)
        self.pushButton_reset_drainage_line_audit.setGeometry(QtCore.QRect(10, 50, 151, 23))
        self.pushButton_reset_drainage_line_audit.setObjectName("pushButton_reset_drainage_line_audit")
        self.pushButton_reset_drainage_area_audit = QtWidgets.QPushButton(self.groupBox_54)
        self.pushButton_reset_drainage_area_audit.setGeometry(QtCore.QRect(10, 80, 151, 23))
        self.pushButton_reset_drainage_area_audit.setObjectName("pushButton_reset_drainage_area_audit")
        self.groupBox_46 = QtWidgets.QGroupBox(self.groupBox_53)
        self.groupBox_46.setGeometry(QtCore.QRect(220, 20, 191, 311))
        self.groupBox_46.setObjectName("groupBox_46")
        self.pushButton_drop_role = QtWidgets.QPushButton(self.groupBox_46)
        self.pushButton_drop_role.setGeometry(QtCore.QRect(10, 280, 171, 23))
        self.pushButton_drop_role.setObjectName("pushButton_drop_role")
        self.pushButton_check_role = QtWidgets.QPushButton(self.groupBox_46)
        self.pushButton_check_role.setGeometry(QtCore.QRect(10, 20, 171, 23))
        self.pushButton_check_role.setObjectName("pushButton_check_role")
        self.listWidget_role = QtWidgets.QListWidget(self.groupBox_46)
        self.listWidget_role.setGeometry(QtCore.QRect(10, 50, 171, 161))
        self.listWidget_role.setObjectName("listWidget_role")
        self.pushButton_disable_role = QtWidgets.QPushButton(self.groupBox_46)
        self.pushButton_disable_role.setGeometry(QtCore.QRect(10, 250, 171, 23))
        self.pushButton_disable_role.setObjectName("pushButton_disable_role")
        self.pushButton_enable_role = QtWidgets.QPushButton(self.groupBox_46)
        self.pushButton_enable_role.setGeometry(QtCore.QRect(10, 220, 171, 23))
        self.pushButton_enable_role.setObjectName("pushButton_enable_role")
        self.groupBox_56 = QtWidgets.QGroupBox(self.groupBox_53)
        self.groupBox_56.setGeometry(QtCore.QRect(10, 20, 201, 111))
        self.groupBox_56.setObjectName("groupBox_56")
        self.lineEdit_role = QtWidgets.QLineEdit(self.groupBox_56)
        self.lineEdit_role.setGeometry(QtCore.QRect(70, 20, 111, 20))
        self.lineEdit_role.setObjectName("lineEdit_role")
        self.pushButton_create_role = QtWidgets.QPushButton(self.groupBox_56)
        self.pushButton_create_role.setGeometry(QtCore.QRect(80, 80, 81, 23))
        self.pushButton_create_role.setObjectName("pushButton_create_role")
        self.lineEdit_role_password = QtWidgets.QLineEdit(self.groupBox_56)
        self.lineEdit_role_password.setGeometry(QtCore.QRect(70, 50, 111, 20))
        self.lineEdit_role_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_role_password.setObjectName("lineEdit_role_password")
        self.label = QtWidgets.QLabel(self.groupBox_56)
        self.label.setGeometry(QtCore.QRect(10, 20, 61, 16))
        self.label.setObjectName("label")
        self.label_6 = QtWidgets.QLabel(self.groupBox_56)
        self.label_6.setGeometry(QtCore.QRect(10, 50, 51, 16))
        self.label_6.setObjectName("label_6")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.label_11 = QtWidgets.QLabel(self.tab_7)
        self.label_11.setGeometry(QtCore.QRect(230, 150, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_11.setOpenExternalLinks(False)
        self.label_11.setObjectName("label_11")
        self.label_pghydro_schema_version = QtWidgets.QLabel(self.tab_7)
        self.label_pghydro_schema_version.setGeometry(QtCore.QRect(220, 320, 171, 20))
        self.label_pghydro_schema_version.setText("")
        self.label_pghydro_schema_version.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pghydro_schema_version.setObjectName("label_pghydro_schema_version")
        self.label_13 = QtWidgets.QLabel(self.tab_7)
        self.label_13.setGeometry(QtCore.QRect(230, 120, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_12 = QtWidgets.QLabel(self.tab_7)
        self.label_12.setGeometry(QtCore.QRect(60, 100, 161, 181))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap(":/plugins/PghydroTools/Logo_pghydro_hexa.png"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.label_14 = QtWidgets.QLabel(self.tab_7)
        self.label_14.setGeometry(QtCore.QRect(230, 190, 411, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.tabWidget.addTab(self.tab_7, "")
        self.groupBox_5 = QtWidgets.QGroupBox(PghydroToolsDialogBase)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 390, 661, 231))
        self.groupBox_5.setObjectName("groupBox_5")
        self.console = QtWidgets.QTextEdit(self.groupBox_5)
        self.console.setGeometry(QtCore.QRect(10, 20, 641, 201))
        self.console.setObjectName("console")

        self.retranslateUi(PghydroToolsDialogBase)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(PghydroToolsDialogBase)

    def retranslateUi(self, PghydroToolsDialogBase):
        _translate = QtCore.QCoreApplication.translate
        PghydroToolsDialogBase.setWindowTitle(_translate("PghydroToolsDialogBase", "Pghydro Tools"))
        self.groupBox.setTitle(_translate("PghydroToolsDialogBase", "1 - Connection Data"))
        self.label_1.setText(_translate("PghydroToolsDialogBase", "Host"))
        self.label_2.setText(_translate("PghydroToolsDialogBase", "Port"))
        self.label_3.setText(_translate("PghydroToolsDialogBase", "Database"))
        self.label_4.setText(_translate("PghydroToolsDialogBase", "Username"))
        self.label_5.setText(_translate("PghydroToolsDialogBase", "Password"))
        self.lineEdit_host.setText(_translate("PghydroToolsDialogBase", "localhost"))
        self.lineEdit_port.setText(_translate("PghydroToolsDialogBase", "5432"))
        self.lineEdit_base.setText(_translate("PghydroToolsDialogBase", "pghydro"))
        self.lineEdit_user.setText(_translate("PghydroToolsDialogBase", "postgres"))
        self.lineEdit_password.setText(_translate("PghydroToolsDialogBase", "postgres"))
        self.pushButton_connect_database.setText(_translate("PghydroToolsDialogBase", "Test Connection"))
        self.lineEdit_schema.setText(_translate("PghydroToolsDialogBase", "pghydro"))
        self.label_8.setText(_translate("PghydroToolsDialogBase", "Scheme"))
        self.pushButton_create_database.setText(_translate("PghydroToolsDialogBase", "Create Spatial Database\n"
" And PgHydro Scheme"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("PghydroToolsDialogBase", "Connect Spatial Database"))
        self.groupBox_2.setTitle(_translate("PghydroToolsDialogBase", "2 - Import Geometry Table to PgHydro Scheme"))
        self.groupBox_3.setTitle(_translate("PghydroToolsDialogBase", "Drainage Line"))
        self.pushButton_import_drainage_line.setText(_translate("PghydroToolsDialogBase", "Import Drainage Line"))
        self.label_7.setText(_translate("PghydroToolsDialogBase", "Geometry Table"))
        self.label_9.setText(_translate("PghydroToolsDialogBase", "Name Column"))
        self.groupBox_4.setTitle(_translate("PghydroToolsDialogBase", "Drainage Area"))
        self.label_10.setText(_translate("PghydroToolsDialogBase", "Geometry Table"))
        self.pushButton_import_drainage_area.setText(_translate("PghydroToolsDialogBase", "Import Drainage Area"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_9), _translate("PghydroToolsDialogBase", "Import Spatial Data"))
        self.groupBox_6.setTitle(_translate("PghydroToolsDialogBase", "3.1 - Geometric Consistency"))
        self.groupBox_8.setTitle(_translate("PghydroToolsDialogBase", "Non-Simple Geometry"))
        self.pushButton_MakeDrainageLineSimple.setText(_translate("PghydroToolsDialogBase", "Simplify"))
        self.label_41.setText(_translate("PghydroToolsDialogBase", "pghft_drainagelineisnotsimple"))
        self.groupBox_9.setTitle(_translate("PghydroToolsDialogBase", "Invalid Geometry"))
        self.pushButton_MakeDrainageLineValid.setText(_translate("PghydroToolsDialogBase", "Validate"))
        self.label_42.setText(_translate("PghydroToolsDialogBase", "pghft_drainagelineisnotvalid"))
        self.pushButton_Check_DrainageLineGeometryConsistencies.setText(_translate("PghydroToolsDialogBase", "Check All"))
        self.lineEdit_DrainageLinePrecision.setText(_translate("PghydroToolsDialogBase", "0.0000001"))
        self.label_25.setText(_translate("PghydroToolsDialogBase", "PRECISION:"))
        self.lineEdit_DrainageLineOffset.setText(_translate("PghydroToolsDialogBase", "1"))
        self.label_28.setText(_translate("PghydroToolsDialogBase", "OFFSET(drn_pk):"))
        self.groupBox_7.setTitle(_translate("PghydroToolsDialogBase", "Non-Single Geometry"))
        self.pushButton_ExplodeDrainageLine.setText(_translate("PghydroToolsDialogBase", "Explode"))
        self.label_43.setText(_translate("PghydroToolsDialogBase", "pghft_drainagelineisnotsingle"))
        self.groupBox_36.setTitle(_translate("PghydroToolsDialogBase", "3.2 - Topological Consistency - Part I"))
        self.pushButton_Check_DrainageLineTopologyConsistencies_1.setText(_translate("PghydroToolsDialogBase", "Check All"))
        self.groupBox_38.setTitle(_translate("PghydroToolsDialogBase", "Geometry WITHIN Geometry"))
        self.pushButton_DeleteDrainageLineWithinDrainageLine.setText(_translate("PghydroToolsDialogBase", "Delete"))
        self.label_44.setText(_translate("PghydroToolsDialogBase", "pghft_drainagelinewithindrainageline"))
        self.groupBox_41.setTitle(_translate("PghydroToolsDialogBase", "Geometry OVERLAP Geometry"))
        self.label_26.setText(_translate("PghydroToolsDialogBase", "Manual Editing"))
        self.label_45.setText(_translate("PghydroToolsDialogBase", "pghft_drainagelineoverlapdrainageline"))
        self.groupBox_11.setTitle(_translate("PghydroToolsDialogBase", "Geometry With LOOPS "))
        self.label_27.setText(_translate("PghydroToolsDialogBase", "Manual Editing"))
        self.label_46.setText(_translate("PghydroToolsDialogBase", "pghft_drainagelineloops"))
        self.groupBox_39.setTitle(_translate("PghydroToolsDialogBase", "3.3 - Topological Consistency - Part II"))
        self.pushButton_Check_DrainageLineTopologyConsistencies_2.setText(_translate("PghydroToolsDialogBase", "Check All"))
        self.groupBox_40.setTitle(_translate("PghydroToolsDialogBase", "Geometry CROSS Geometry"))
        self.label_47.setText(_translate("PghydroToolsDialogBase", "pghft_drainagelinecrossdrainagelines"))
        self.groupBox_42.setTitle(_translate("PghydroToolsDialogBase", "Geometry TOUCH Geometry"))
        self.label_48.setText(_translate("PghydroToolsDialogBase", "pghft_drainagelinetouchdrainageline"))
        self.pushButton_BreakDrainageLines.setText(_translate("PghydroToolsDialogBase", "Break Lines"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("PghydroToolsDialogBase", "Consist Drainage Line"))
        self.groupBox_12.setTitle(_translate("PghydroToolsDialogBase", "4.1 - Create Drainage Line Network"))
        self.groupBox_14.setTitle(_translate("PghydroToolsDialogBase", "Nodes with Valence = 2 (Pseudo-Node)"))
        self.pushButton_UnionDrainageLineValence2.setText(_translate("PghydroToolsDialogBase", "Spatial Union"))
        self.label_49.setText(_translate("PghydroToolsDialogBase", "pghft_pointvalencevalue2"))
        self.groupBox_15.setTitle(_translate("PghydroToolsDialogBase", "Nodes with Valence >=4 (Multiple Confl.)"))
        self.label_30.setText(_translate("PghydroToolsDialogBase", "Manual Editing"))
        self.label_50.setText(_translate("PghydroToolsDialogBase", "pghft_pointvalencevalue4"))
        self.pushButton_Execute_Network_Topology.setText(_translate("PghydroToolsDialogBase", "Execute"))
        self.label_29.setText(_translate("PghydroToolsDialogBase", "OFFSET(drp_pk):"))
        self.lineEdit_DrainagePointOffset.setText(_translate("PghydroToolsDialogBase", "1"))
        self.groupBox_13.setTitle(_translate("PghydroToolsDialogBase", "4.2 - Identify Network Nodes"))
        self.pushButton_UpdateShorelineStartingPoint.setText(_translate("PghydroToolsDialogBase", "Start Node*"))
        self.pushButton_UpdateShorelineEndingPoint.setText(_translate("PghydroToolsDialogBase", "End Node"))
        self.label_40.setText(_translate("PghydroToolsDialogBase", "* Only available on coast basin"))
        self.groupBox_16.setTitle(_translate("PghydroToolsDialogBase", "4.3 - Connectivity and Flow Direction"))
        self.groupBox_17.setTitle(_translate("PghydroToolsDialogBase", "Drainage Lines  Disconnected"))
        self.label_31.setText(_translate("PghydroToolsDialogBase", "Manual Editing"))
        self.label_51.setText(_translate("PghydroToolsDialogBase", "pghft_drainagelineisdisconnected"))
        self.groupBox_18.setTitle(_translate("PghydroToolsDialogBase", "Divergent Drainage Points"))
        self.label_32.setText(_translate("PghydroToolsDialogBase", "Manual Editing"))
        self.label_52.setText(_translate("PghydroToolsDialogBase", "pghft_pointdivergent"))
        self.pushButton_Check_Execute_Flow_Direction.setText(_translate("PghydroToolsDialogBase", "Execute"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("PghydroToolsDialogBase", "Consist Drainage Line Network"))
        self.groupBox_19.setTitle(_translate("PghydroToolsDialogBase", "5.2 - Topological Consistency"))
        self.groupBox_23.setTitle(_translate("PghydroToolsDialogBase", "Geometry OVERLAP Geometry"))
        self.pushButton_RemoveDrainageAreaOverlap.setText(_translate("PghydroToolsDialogBase", "Remove"))
        self.label_57.setText(_translate("PghydroToolsDialogBase", "pghft_drainageareaoverlapdrainagearea"))
        self.groupBox_24.setTitle(_translate("PghydroToolsDialogBase", "Geometry WITHIN Geometry"))
        self.pushButton_DeleteDrainageAreaWithinDrainageArea.setText(_translate("PghydroToolsDialogBase", "Delete"))
        self.label_56.setText(_translate("PghydroToolsDialogBase", "pghft_drainageareawithindrainagearea"))
        self.pushButton_Check_DrainageAreaTopologyConsistencies.setText(_translate("PghydroToolsDialogBase", "Check All"))
        self.groupBox_10.setTitle(_translate("PghydroToolsDialogBase", "5.1 - Geometric Consistency"))
        self.groupBox_44.setTitle(_translate("PghydroToolsDialogBase", "Non-Simple Geometry"))
        self.pushButton_MakeDrainageAreaSimple.setText(_translate("PghydroToolsDialogBase", "Simplify"))
        self.label_53.setText(_translate("PghydroToolsDialogBase", "pghft_drainageareaisnotsingle"))
        self.groupBox_45.setTitle(_translate("PghydroToolsDialogBase", "Invalid Geometry"))
        self.pushButton_MakeDrainageAreaValid.setText(_translate("PghydroToolsDialogBase", "Validate"))
        self.label_54.setText(_translate("PghydroToolsDialogBase", "pghft_drainageareaisnotvalid"))
        self.lineEdit_DrainageAreaPrecision.setText(_translate("PghydroToolsDialogBase", "0.0000001"))
        self.label_33.setText(_translate("PghydroToolsDialogBase", "PRECISION:"))
        self.lineEdit_DrainageAreaOffset.setText(_translate("PghydroToolsDialogBase", "1"))
        self.label_34.setText(_translate("PghydroToolsDialogBase", "OFFSET(dra_pk):"))
        self.pushButton_Check_DrainageAreaGeometryConsistencies.setText(_translate("PghydroToolsDialogBase", "Check All"))
        self.groupBox_43.setTitle(_translate("PghydroToolsDialogBase", "Non-Single Geometry"))
        self.pushButton_ExplodeDrainageArea.setText(_translate("PghydroToolsDialogBase", "Explode"))
        self.label_55.setText(_translate("PghydroToolsDialogBase", "pghft_drainageareaisnotsingle"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("PghydroToolsDialogBase", "Consist Drainage Area"))
        self.groupBox_25.setTitle(_translate("PghydroToolsDialogBase", "6 - Topological Consistency"))
        self.groupBox_27.setTitle(_translate("PghydroToolsDialogBase", "Drainage Line WITHOUT Drainage Area"))
        self.label_35.setText(_translate("PghydroToolsDialogBase", "Manual Editing"))
        self.label_58.setText(_translate("PghydroToolsDialogBase", "pghft_drainagelinenodrainagearea"))
        self.groupBox_28.setTitle(_translate("PghydroToolsDialogBase", "Drainage Area >1:1 Drainage Line"))
        self.label_36.setText(_translate("PghydroToolsDialogBase", "Manual Editing"))
        self.label_59.setText(_translate("PghydroToolsDialogBase", "pghft_drainageareamoreonedrainageline"))
        self.groupBox_29.setTitle(_translate("PghydroToolsDialogBase", "Drainage Line >1:1 Drainage Area"))
        self.label_37.setText(_translate("PghydroToolsDialogBase", "Manual Editing"))
        self.label_60.setText(_translate("PghydroToolsDialogBase", "pghft_drainagelinemoreonedrainagearea"))
        self.pushButton_Check_DrainageAreaDrainageLineConsistencies.setText(_translate("PghydroToolsDialogBase", "Check All"))
        self.groupBox_26.setTitle(_translate("PghydroToolsDialogBase", "Drainage Area WITHOUT Drainage Line"))
        self.pushButton_Union_DrainageAreaNoDrainageLine.setText(_translate("PghydroToolsDialogBase", "Spatial Union"))
        self.label_61.setText(_translate("PghydroToolsDialogBase", "pghft_drainageareanodrainageline"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("PghydroToolsDialogBase", "Consist Drainage Line x Drainage Area"))
        self.groupBox_31.setTitle(_translate("PghydroToolsDialogBase", "7 - Execute Final Hydrographic Information"))
        self.groupBox_32.setTitle(_translate("PghydroToolsDialogBase", "Main Procedures"))
        self.pushButton_Principal_Procedure.setText(_translate("PghydroToolsDialogBase", "Execute"))
        self.checkBox_CalculateDrainageLineLength.setText(_translate("PghydroToolsDialogBase", "Update Drainage Line Length"))
        self.checkBox_CalculateDrainageAreaArea.setText(_translate("PghydroToolsDialogBase", "Update Drainage Area Area"))
        self.checkBox_CalculateDistanceToSea.setText(_translate("PghydroToolsDialogBase", "Update Sea Distance (OFFSET):"))
        self.checkBox_CalculateUpstreamArea.setText(_translate("PghydroToolsDialogBase", "Update Upstream Area"))
        self.checkBox_CalculateUpstreamDrainageLine.setText(_translate("PghydroToolsDialogBase", "Update Upstream Drainage Line"))
        self.checkBox_CalculateDownstreamDrainageLine.setText(_translate("PghydroToolsDialogBase", "Update Downstream Drainage Line"))
        self.checkBox_Calculate_Pfafstetter_Codification.setText(_translate("PghydroToolsDialogBase", "Calculate Otto Pfafstetter Basin Coding"))
        self.checkBox_UpdatePfafstetterBasinCode.setText(_translate("PghydroToolsDialogBase", "Update Otto Pfafstetter Basin Coding:"))
        self.checkBox_UpdateWatercourse.setText(_translate("PghydroToolsDialogBase", "Update Water Course"))
        self.checkBox_UpdateWatercourse_Point.setText(_translate("PghydroToolsDialogBase", "Update Water Course Points"))
        self.checkBox_calculatestrahlernumber.setText(_translate("PghydroToolsDialogBase", "Update Strahler Order"))
        self.lineEdit_srid_drainage_line_length.setText(_translate("PghydroToolsDialogBase", "3857"))
        self.lineEdit_srid_drainage_area_area.setText(_translate("PghydroToolsDialogBase", "3857"))
        self.label_21.setText(_translate("PghydroToolsDialogBase", "SRID:"))
        self.label_22.setText(_translate("PghydroToolsDialogBase", "SRID:"))
        self.lineEdit_factor_drainage_line_length.setText(_translate("PghydroToolsDialogBase", "1000"))
        self.lineEdit_factor_drainage_area_area.setText(_translate("PghydroToolsDialogBase", "1000000"))
        self.label_23.setText(_translate("PghydroToolsDialogBase", "Factor:"))
        self.label_24.setText(_translate("PghydroToolsDialogBase", "Factor:"))
        self.lineEdit_distance_to_sea.setText(_translate("PghydroToolsDialogBase", "0"))
        self.lineEdit_pfafstetter_basin_code.setText(_translate("PghydroToolsDialogBase", "0"))
        self.checkBox_UpdatePfafstetterWatercourseCode.setText(_translate("PghydroToolsDialogBase", "Update Otto Pfafstetter Water Course Code"))
        self.checkBox_InsertColumnPfafstetterBasinCodeLevel.setText(_translate("PghydroToolsDialogBase", "Add Pfafstetter Basin Coding Columns"))
        self.checkBox_updateshoreline.setText(_translate("PghydroToolsDialogBase", "Update Shoreline (if exists)"))
        self.checkBox_TurnOnKeysIndex.setText(_translate("PghydroToolsDialogBase", "Turn On Indexes, PKs and FKs"))
        self.checkBox_UpdateDomainColumn.setText(_translate("PghydroToolsDialogBase", "Update Water Course Domain"))
        self.checkBox_UpdateWatershed.setText(_translate("PghydroToolsDialogBase", "Update Watersheds <="))
        self.lineEdit_watershed_pfafstetter_max_code.setText(_translate("PghydroToolsDialogBase", "6"))
        self.checkBox_TurnOffKeysIndex.setText(_translate("PghydroToolsDialogBase", "Turn Off Indexes, PKs and FKs"))
        self.checkBox_Vacuum_Database.setText(_translate("PghydroToolsDialogBase", "Vacuum Database"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("PghydroToolsDialogBase", "Final Hydrographic Information"))
        self.groupBox_30.setTitle(_translate("PghydroToolsDialogBase", "8 - Update Output Geometry Tables"))
        self.pushButton_UpdateExportTables.setText(_translate("PghydroToolsDialogBase", "Execute"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("PghydroToolsDialogBase", "Update Output Geometry Tables"))
        self.groupBox_47.setTitle(_translate("PghydroToolsDialogBase", "9 - Hydronymia Systematization (river names)"))
        self.groupBox_52.setTitle(_translate("PghydroToolsDialogBase", "9.4 Finish Hydronymia Systematization"))
        self.pushButton_Stop_Systematize_Hydronym.setText(_translate("PghydroToolsDialogBase", "Execute"))
        self.groupBox_34.setTitle(_translate("PghydroToolsDialogBase", "9.2 Hydronymia Editing"))
        self.groupBox_51.setTitle(_translate("PghydroToolsDialogBase", "9.2.3 Update Original Names"))
        self.pushButton_Update_OriginalHydronym.setText(_translate("PghydroToolsDialogBase", "Execute"))
        self.groupBox_59.setTitle(_translate("PghydroToolsDialogBase", "9.2.2 Review Systematized Names"))
        self.label_39.setText(_translate("PghydroToolsDialogBase", "Manual Table Editing"))
        self.groupBox_60.setTitle(_translate("PghydroToolsDialogBase", "9.2.1 Systematize Names"))
        self.pushButton_Systematize_Hydronym.setText(_translate("PghydroToolsDialogBase", "Execute"))
        self.groupBox_58.setTitle(_translate("PghydroToolsDialogBase", "9.1 Start Hydronymia Systematization"))
        self.pushButton_Start_Systematize_Hydronym.setText(_translate("PghydroToolsDialogBase", "Execute"))
        self.groupBox_50.setTitle(_translate("PghydroToolsDialogBase", "9.3 Confluent Hydronymia"))
        self.pushButton_Check_ConfluenceHydronym.setText(_translate("PghydroToolsDialogBase", "Check"))
        self.label_38.setText(_translate("PghydroToolsDialogBase", "Manual Vector Editing"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("PghydroToolsDialogBase", "Hydronymia"))
        self.groupBox_53.setTitle(_translate("PghydroToolsDialogBase", "10 - Multi-User Editing"))
        self.groupBox_54.setTitle(_translate("PghydroToolsDialogBase", "10.3 Log Management"))
        self.pushButton_turn_off_audit.setText(_translate("PghydroToolsDialogBase", "Turn Off"))
        self.pushButton_turn_on_audit.setText(_translate("PghydroToolsDialogBase", "Turn On"))
        self.pushButton_reset_drainage_line_audit.setText(_translate("PghydroToolsDialogBase", "Reset Drainage Line Log"))
        self.pushButton_reset_drainage_area_audit.setText(_translate("PghydroToolsDialogBase", "Reset Drainage Area Log"))
        self.groupBox_46.setTitle(_translate("PghydroToolsDialogBase", "10.2 View Users"))
        self.pushButton_drop_role.setText(_translate("PghydroToolsDialogBase", "Drop Selected User"))
        self.pushButton_check_role.setText(_translate("PghydroToolsDialogBase", "View Users"))
        self.listWidget_role.setSortingEnabled(True)
        self.pushButton_disable_role.setText(_translate("PghydroToolsDialogBase", "Revoke Selected User"))
        self.pushButton_enable_role.setText(_translate("PghydroToolsDialogBase", "Grant Selected User"))
        self.groupBox_56.setTitle(_translate("PghydroToolsDialogBase", "10.1 Criate User"))
        self.pushButton_create_role.setText(_translate("PghydroToolsDialogBase", "Create"))
        self.label.setText(_translate("PghydroToolsDialogBase", "Username:"))
        self.label_6.setText(_translate("PghydroToolsDialogBase", "Password:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("PghydroToolsDialogBase", "Multi-User Editing"))
        self.label_11.setText(_translate("PghydroToolsDialogBase", "www.pghydro.org"))
        self.label_13.setText(_translate("PghydroToolsDialogBase", "PgHydro Tools Version 2.4"))
        self.label_14.setText(_translate("PghydroToolsDialogBase", " REQUIREMENTS:\n"
" -Postgresql version 9.1+\n"
" -PostGIS version 2.0+\n"
" -PgHydro version 6.4: https://github.com/pghydro/pghydro/tree/master"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("PghydroToolsDialogBase", "Version"))
        self.groupBox_5.setTitle(_translate("PghydroToolsDialogBase", "Console"))

import resources_rc
from qgis.PyQt.QtWidgets import QWidget

class PghydroToolsDialog(QWidget, Ui_PghydroToolsDialogBase):
    def __init__(self, parent = None):
        """
        Constructor
        """
        super(PghydroToolsDialog, self).__init__(parent)
        self.setupUi(self)